version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: link_harvester
      MYSQL_ROOT_PASSWORD: link_harvester

  # Application Service
  app:
    container_name: link_harvester
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  worker:
    build:
      context: ./php
      dockerfile: Dockerfile
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
    volumes:
      - ./src:/var/www
      - ./worker/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    depends_on:
      - app
